name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Set Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_12.5.app
    - name: Build Debug for macosx
      env:
        SNAPSHOT_REFERENCE_DIR: ${{ github.workspace }}/Tests/SnapshotTestingExTests/__Snapshots__
      run: xcodebuild -scheme SnapshotTestingEx -configuration Debug -sdk macosx build test

#      run: echo "${{ env.SNAPSHOT_REFERENCE_DIR }}"
#      run: xcodebuild -scheme SnapshotTestingEx -configuration Debug -sdk macosx build test
#    - name: Build Debug for iphonesimulator
#      run: xcodebuild -scheme SnapshotTestingEx -configuration Debug -sdk iphonesimulator build
#      run: xcodebuild -scheme SnapshotTestingEx -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=14.5,name=iPhone 11' build test
#    - name: Build Debug for appletvsimulator
#      run: xcodebuild -scheme SnapshotTestingEx -configuration Debug -sdk appletvsimulator build
#      run: xcodebuild -scheme SnapshotTestingEx -configuration Debug -sdk appletvsimulator -destination 'platform=tvOS Simulator,OS=14.5,name=Apple TV' build test 
